### ISSUE TITLE
Support seekable stdin properly

### ISSUE THREAD

**Issue by xanonid** [neosmart/tac#2]
Currently, stdin is always buffered, but there is a mechanism to distinguish between pipes and seekable files, cf. e.g. https://unix.stackexchange.com/questions/502518/problems-when-test-whether-standard-input-is-capable-of-seeking

This would allow to use `tac < big_file` more efficient.

**Comment by mqudsi** [comment]
Nice find. Given the caveat about non-seekable pipes allowed to return true, an `istty()` check combined with an attempt to seek should give the right result there.

The only question is whether that is sufficient to pass stdin in to a call to `mmap(2)` or if we'd have to add an alternate buffer-backed search for this case.

**Comment by xanonid** [comment]
I would suggest to try mmap first for any input and fall back to a buffer-backed search if necessary. Also files passed as regular arguments could be e.g. named pipes or character devices that are usually not mmap-able. There might be also filesystems which support not (yet) mmap for regular files.

**Comment by mqudsi** [comment]
Good idea. I've implemented just that in b9e134a and it seems to work OK for some basic tests (skips buffering for `tac - <foo.txt` and correctly buffers for `foo | tac -`).

Thank you!

**Comment by mqudsi** [comment]
> Also files passed as regular arguments could be e.g. named pipes or character devices that are usually not mmap-able. There might be also filesystems which support not (yet) mmap for regular files.

We currently error out for these when the `mmap()` call fails. We *could* switch to buffering but I don't think that's a great idea because the use case seems extremely niche to the point where it's probably more likely to be a mistake (imho, please correct me if I'm wrong) in which case we don't want to hang duplicating their entire drive/partition into a temporary file (there wouldn't even be any feedback akin to when the same mistake is made with `cat` since no junk will be posted to the terminal until the buffering has completed).
